### ISSUE TITLE
Waiting servers (0) is less than MinSpareServers (5). Creating new child.

### ISSUE THREAD

**Issue by hplc** [tinyproxy/tinyproxy#199]
CentOS release 6.9 (Final)
First used the Version 1.8.3 epel package.
Then tried compiling from Version 1.10.0 source code.

After some time, all result in "Waiting servers (0) is less than MinSpareServers (5). Creating new child. "
Then the client has no internet connection any more, and wait a long time to timeout.

But while check processes, there are enough processes (maybe 100) shows:
`/usr/sbin/tinyproxy -c /etc/tinyproxy/tinyproxy.conf`

After a service restart everything back to normal. Now I put `service tinyproxy restart` in crontab to run every hour to deal with this problem.

**Comment by rofl0r** [comment]
maybe your consumer (the client connecting to the proxy) doesn't close stale connections properly ?

**Comment by hplc** [comment]
No facebook app, just some educational apps for kids.

I tried MaxClients 500, still the same problem.

After a day or some the processes will reach 500, it seems all the process would not work for the client, tinyproxy try to spawn new child, but it reached the MaxClients limit, so the tinyproxy just stuck there.

**Comment by rofl0r** [comment]
sounds to me as if that apps has a resource leak (doesn't close sockets after use). what happens when you close the app on one of the tablets, when the tinyproxy limit is hit ?

**Comment by rofl0r** [comment]
> Is it possible that openvpn doesn't close connections correctly while tunneling through proxies? (it uses CONNECT statements)

we can find out if you run openvpn through strace (`strace -o log.txt -s 256 -f openvpn --bar --foo`) and then grep the log for, and count the number of, close and socket syscalls

**Comment by Architektor** [comment]
Having the same problem, started up playing around with default `MaxSpareServers 20` and the proxy got stuck at logging `Waiting servers (0) is less than MinSpareServers (5). Creating new child.` continiously. Don't have much time to dig deeper now, but facing the same thing i believe

**Comment by rofl0r** [comment]
in order to diagnose the issue further, one of you guys gotta try if the issue gets fixed when the app in question is closed (so all its stale sockets are closed). if that fixes it, the problem is the app in question, if not there's something wrong with tinyproxy and we need to dig deeper.

**Comment by Architektor** [comment]
> in order to diagnose the issue further, one of you guys gotta try if the issue gets fixed when the app in question is closed (so all its stale sockets are closed). if that fixes it, the problem is the app in question, if not there's something wrong with tinyproxy and we need to dig deeper.

i mean the proxy is stuck, thus not working anymore. Do you mean like if a single proxy user will open a "wrong app" and the whole proxy server hangs for all the users forever until restarting the service is an *app* problem not proxy server problem?

**Comment by rofl0r** [comment]
forever ? stale connections are auto-closed after a user-configurable timeout.
your proxy is configured to take a specific maximal number of connections.
if those connections are held open by some sloppily-programmed app, the behaviour you mention is expected. so would you PRETTY PLEASE try to kill the app that consumed the initial set of sockets and then report if that makes the proxy responsive again, instead of playing the clown?

**Comment by Architektor** [comment]
> forever ? stale connections are auto-closed after a user-configurable timeout.
> your proxy is configured to take a specific maximal number of connections.
> if those connections are held open by some sloppily-programmed app, the behaviour you mention is expected. so would you PRETTY PLEASE try to kill the app that consumed the initial set of sockets and then report if that makes the proxy responsive again, instead of playing the clown?

okay man chill down i didn't mean to hurt your feelings in any hurting way
sorry if my comment looks harshy, i sincerely want the problem to be fixed for all of us,
but i don't have much time now for debugging and diagnosing the thing.
just understand my situation: 
i need a fast and portable proxy solution, 
i google it,
i find the beautiful "tinyproxy" which fits all my needs,
i set it up on EC2 and just forget about it,
after a while, nothing goes though it,
i go to logs, open em and see the picture:
```
Waiting servers (0) is less than MinSpareServers (5). Creating new child
Waiting servers (0) is less than MinSpareServers (5) ...
Waiting servers (0) is less than MinSpareServers (5) ...
Waiting servers (0) is less than MinSpareServers (5) ...
... and so on 15 more times
```
it's my *issue*, so
i open up this repo, go to issues and *whoa*, i see the exact same issue,
so i add up my report on a similar situation

please don't be mad at me, i will try to help detecting this on a weekend

**Comment by hplc** [comment]
Close app doesn't help.
Even I poweroff iPad, reboot iPad doesn't help.

Just reboot tinyproxy helps.

**Comment by rofl0r** [comment]
stale.conf
```
User nobody
Group nobody
Port 7777
Timeout 600
LogLevel Info
MaxClients 40
MinSpareServers 5
MaxSpareServers 20
StartServers 10
MaxRequestsPerChild 0
Allow 127.0.0.1
ViaProxyName "tinyproxy"
```

run `tinyproxy -d -c stale.conf`

test.py
```py
from http2 import RsHttp, _parse_url
from rocksock import RocksockProxyFromURL
import time

connections = []

def get_connection():
        url = 'https://www.facebook.com'
        proxies = [RocksockProxyFromURL('http://localhost:7777')]
        host, port, use_ssl, uri = _parse_url(url)
        http = RsHttp(host=host, port=port, timeout=15, ssl=use_ssl, follow_redirects=True, auto_set_cookies=True, keep_alive=True, proxies=proxies)
        #http.debugreq = True
        while not http.connect():
                print "sorry, couldn't connect"
        else:
                hdr  = http.head(uri)
                #hdr, res = http.get(uri)
        return http


if __name__ == '__main__':
        max_conns = 30
        while 1:
                print "loop"
                while len(connections) < max_conns:
                        print "current connections: %d"%len(connections)
                        conn = get_connection()
                        connections.append(conn)

                for c in connections:
                        c.head('/')

                time.sleep(1)
                max_conns += 5
```
test.py requires 2 files which can be found in my [twatscrape](https://github.com/rofl0r/twatscrape) project, so its best you clone that repo and put test.py into that directory, then run python2 test.py

what i'm observing is that tinyproxy behaves exactly as specified, as soon as the test app created 40 connections, we get the message in the in the title.

```
current connections: 38
current connections: 39
loop
current connections: 40
timeout reached on operation
timeout reached on operation
timeout reached on operation
```

you can also count the number of threads tinyproxy uses:
```
$ ps aux | grep stale | wc -l
42
```

as soon as i hit CTRL-C in the python test program, the sockets are released and the server accepts new connections.

this basically proves that tinyproxy works as designed, there needs to be something running on at least one of your devices that exhausts all connections, without closing stale connections.

**Comment by CappyT** [comment]
Thanks for all the effort put into testing this.

Have you got any plans to kill inactive connections after a specified timeout? This could be really useful for applications that aren't behaving correctly or when a connection suddenly drops client-side.

**Comment by rofl0r** [comment]
there are currently no plans, but this is a good idea. would you mind opening a feature request issue for that ?

**Comment by rofl0r** [comment]
oh, actually that feature already exists:
```
# Timeout: The maximum number of seconds of inactivity a connection is
# allowed to have before it is closed by tinyproxy.
# 
Timeout 600

```

**Comment by rofl0r** [comment]
C ain't C++.

if you think this didn't happen in the past and want to help, you could use `git bisect` to find the commit that introduced the issue.
here's a how-to: http://webchick.net/node/99

**Comment by cutalion** [comment]
I had the same issue. Tinyproxy was working for about 6 months without restart on DigitalOcean VPS. I even forgot about it.

2 days ago I updated the kernel from (3.13.0-144.193 to 4.4.0-139.165). 
Today I have this issue.

I restarted tinyproxy, it back to normal. Will check it tomorrow.

**Comment by rofl0r** [comment]
@cutalion only the kernel changed, right ? or did you change tinyproxy version too ?

**Comment by cutalion** [comment]
@rofl0r checked apt/aptitude logs. Nothing about tinyproxy. 
Don't know how to make sure I didn't updated it 2 days ago.
However I installed updates on VPS frequently. 

Didn't know there is a 1.10 version. It seems it has a lot of bug and security fixes and updates. 
So, I'd better install 1.10.

**Comment by rofl0r** [comment]
for testing purposes it'd be better if you keep the old version. the security fixes are not really important (no remote exploits).

**Comment by cutalion** [comment]
np, I'll leave the 1.8.3 version

**Comment by cutalion** [comment]
@rofl0r it happened again today. Any ideas how to debug this? (I left v1.8.3, just reinstalled it from the repo, ubuntu 16.04)

**Comment by cutalion** [comment]
So, the easiest solution for me was to use different port. 
Will see how it works.

**Comment by rofl0r** [comment]
```
INFO      Nov 21 18:18:35 [10132]: process_request: trans Host GET http://localhost:8888/json/v1/server for 6
```
do i read this correctly as recursive connections ?

**Comment by cutalion** [comment]
Don't know. 
What does `process_request: trans` mean?

**Comment by MasteRehm** [comment]
We had the same problem and I found this issue here. After some testing we found the cause: An incorrect client request. This incorrect request brings the tinyproxy to collapse like a house of cards.
System:
- Debian 9 Stretch
- tinyproxy [1.8.4-3~deb9u1](https://packages.debian.org/stretch/tinyproxy)

Configuration:
```
Timeout 600
MaxClients 100
MinSpareServers 5
MaxSpareServers 20
StartServers 10
MaxRequestsPerChild 0
```
I also tried a smaller timeout and increased the MaxSpareServers. Doesn't matter.

After the start of the tinyproxy there are 11 processes with this setup:
```
ps --no-headers -fu tinyproxy | wc -l
11
```
This is the incorrect request (to be precise, the incorrect request starts with line 7):
```
Dez 05 15:07:52 proxy-server tinyproxy[28828]: Connect (file descriptor 6): some-server [192.0.2.42]
Dez 05 15:07:52 proxy-server tinyproxy[28828]: Request (file descriptor 6): CONNECT foreign.host:443 HTTP/1.1
Dez 05 15:07:52 proxy-server tinyproxy[28828]: No upstream proxy for foreign.host
Dez 05 15:07:52 proxy-server tinyproxy[28828]: Established connection to host "foreign.host" using file descriptor 7.
Dez 05 15:07:52 proxy-server tinyproxy[28828]: Not sending client headers to remote machine
Dez 05 15:07:53 proxy-server tinyproxy[28828]: Closed connection between local client (fd:6) and remote client (fd:7)
Dez 05 15:07:52 proxy-server tinyproxy[28827]: Connect (file descriptor 6): some-server [192.0.2.42]
Dez 05 15:07:53 proxy-server tinyproxy[28827]: Request (file descriptor 6): POST https://foreign.host:443/foo/bar HTTP/1.0
Dez 05 15:07:53 proxy-server tinyproxy[28827]: process_request: trans Host POST http://proxy-server:3128https://foreign.host:443/foo/bar for 6
Dez 05 15:07:53 proxy-server tinyproxy[28825]: No upstream proxy for proxy-server
Dez 05 15:07:53 proxy-server tinyproxy[28825]: Established connection to host "proxy-server" using file descriptor 7.
[...]
```
There was only one request from some-server and after that, tinyproxy is going to repeat to process the request again and again. After some minutes there are over 100 processes and he's not going to create new ones or close the old ones. Furthermore the only message in the logfile is the "Waiting servers..." line:
```
$ ps --no-headers -fu tinyproxy | wc -l
101

Dez 05 15:15:28 proxy-server tinyproxy[28818]: Waiting servers (0) is less than MinSpareServers (5). Creating new child.
Dez 05 15:15:33 proxy-server tinyproxy[28818]: Waiting servers (0) is less than MinSpareServers (5). Creating new child.
Dez 05 15:15:38 proxy-server tinyproxy[28818]: Waiting servers (0) is less than MinSpareServers (5). Creating new child.
Dez 05 15:15:43 proxy-server tinyproxy[28818]: Waiting servers (0) is less than MinSpareServers (5). Creating new child.
Dez 05 15:15:48 proxy-server tinyproxy[28818]: Waiting servers (0) is less than MinSpareServers (5). Creating new child.
Dez 05 15:15:53 proxy-server tinyproxy[28818]: Waiting servers (0) is less than MinSpareServers (5). Creating new child.
Dez 05 15:15:58 proxy-server tinyproxy[28818]: Waiting servers (0) is less than MinSpareServers (5). Creating new child.
```
You can say that after that the tinyproxy does not work anymore. Tinyproxy is still running, but does not process new requests. The tinyproxy is in some endless loop and only concerned with itself.

Is there a way to prevent or mitigate this behavior? Or should we call this a bug?

**Comment by MasteRehm** [comment]
Something like this for example:
```
telnet proxy-server 3128
Trying 192.0.2.50
Connected to proxy-server
Escape character is '^]'.
POST https://google.com HTTP/1.0
Host: proxy-server:3128

Connection closed by foreign host.
```

Of course this is wrong (Host = proxy), but after this request the tinyproxy is in the before mentioned endless loop.

**Comment by rofl0r** [comment]
gotcha.
how would you suggest we can detect whether the connection target is our own ip/port in a bullet-proof way ?

**Comment by MasteRehm** [comment]
I can't. I just wanted to share the source of the problem. If this can't be fixed, which I completely understand, that's fine with me.

**Comment by dryliketoast** [comment]
> 
> 
> gotcha.
> how would you suggest we can detect whether the connection target is our own ip/port in a bullet-proof way ?

You could send an unique header with a random key along with the request? then check if the key is known. Not very elegant but could also double as some kind of TTL mechanism, maybe... perhaps.

**Comment by mohag** [comment]
> gotcha.
> how would you suggest we can detect whether the connection target is our own ip/port in a bullet-proof way ?

One method might be to check what it resolves to and check if it is one of the IPs that tinyproxy listens on or an IP on the host. This will fail if NAT is involved....

The problem in [this example](https://github.com/tinyproxy/tinyproxy/issues/199#issuecomment-447388899) seems to be that the connection is to the host in the `Host` header, instead of the one in the URL.

I would expect this to happen in a similar request:
* GET Request for `http://proxy-host:proxy-port/some/url` (absolute-form) with host header of `some-hostname:some-port`
* Proxy connects to `proxy-host:proxy-port` and send `GET /some/url` (origin-form) with host header of `some-hostname:some-port` (This seems non-compliant to [RFC7230](https://tools.ietf.org/html/rfc7230#section-5.4) compliant behaviour seems to be: Proxy connects to `proxy-host:proxy-port`, sends `GET /some/url` and change the host header to `proxy-host:proxy-port`)
* Proxy then taking the request for `/some/url` see it is not an absolute-form request and returns a 404
* Everything gets passed on and closed

Direct HTTPS requests to the proxy in the examples also seems highly unusual - I would have expected to see CONNECT requests for those.

(The loop seems to be one way to get this problem - I don't think that is the issue in the majority of the cases though - mine just randomly built "stuck" instances)

**Comment by rofl0r** [comment]
> You could send an unique header with a random key along with the request? then check if the key is known. Not very elegant but could also double as some kind of TTL mechanism, maybe... perhaps.

that would work, but only for plain http connections. these days, i'd expect the majority of connections to target https, therefore CONNECT method needs to be used.
(btw, there seems to exist a `Max-Forwards` header precisely for this issue).

> One method might be to check what it resolves to and check if it is one of the IPs that tinyproxy listens on or an IP on the host. This will fail if NAT is involved....

right, and additionally one can listen on the *any* interface `0.0.0.0`... which pretty much makes this approach moot. besides, enumerating interfaces is only possible using non-portable functions.

the method i'm currently pondering is keeping a global list of outgoing connection sockaddr addresses *iff* the destination port is equal to the listening port, and check incoming connection addresses against that list. i think this could work out, but this requires my pr #218 to be merged first, because currently tinyproxy uses forked processes with separate address spaces (and the shared memory implementation it uses is horribly inefficient).

**Comment by rofl0r** [comment]
i pushed a fix ^ to my pr #218 (branch `threads`). i'd appreciate testing and feedback, thanks!

**Comment by tarantegui** [comment]
@cutalion Solution worked for me, the same case with netdata

**Comment by rofl0r** [comment]
@tarantegui which solutioon

**Comment by tarantegui** [comment]
> @tarantegui which solutioon

https://github.com/tinyproxy/tinyproxy/issues/199#issuecomment-440703812

**Comment by LucienShui** [comment]
I had the same issue.
Tinyproxy(version 1.10.0) can not working every time after startup about 10 minutes with default settings.
My solution is setting `Timeout` field to `10` instead of `600`.

**Comment by rofl0r** [comment]
@LucienShui please try latest git master, the issue should be fixed there

**Comment by LucienShui** [comment]
@rofl0r okay, thanks a lot!

**Comment by rofl0r** [comment]
@LucienShui please report back after testing whether the issue is resolved for you.

**Comment by aluisioalves123** [comment]
I still don't understand what is the solution for the problem

**Comment by rofl0r** [comment]
@aluisioalves123 use latest tinyproxy 1.11 rc1 release.

**Comment by aluisioalves123** [comment]
can I use it installing with apt-get install?

**Comment by rofl0r** [comment]
> can I use it installing with apt-get install?

i don't think so, since debian maintainers are generally conservative.

> I tried to install using make but doenst succeed

please open a new issue and report the error messages you encountered.

**Comment by aluisioalves123** [comment]
ok, done it :)
