### ISSUE TITLE
build breaks when A2X is not installed

### ISSUE THREAD

**Issue by rofl0r** [tinyproxy/tinyproxy#2]
solution: create manpage as part of "make dist" and ship it with the sources rather than make a2x a hard build dependency

**Comment by obnoxxx** [comment]
Currently the build requires asciidoc. While this dependency pulls in quite a few packages, it is only a build dependency. The runtime system is not affected, hence I do not consider it super urgent. We could at some point change make dist to process the manpages and include them in the tarball.

One point is that some configure-time settings are substituted in the manpage, notably
@VERSION@ and @TINYPROXY_STATHOST@.

**Comment by rofl0r** [comment]
"only a build dependency" is sufficient to cause sufficient pain for users. there are lots of distros like sabotage linux that are source based and as such a build dependency is also indirectly a run dependency since the users needs all this stuff installed. unfortunately this user-is-just-a-consumer-centric (you are not supposed to build stuff, use apt-get) mindset is quite widespread and makes it very hard to get full control over the sw you run on your PC.
note that when i started with sabotage linux targetting a then new libc (musl) without C++ support, it was impossible to compile packages written in C when they used cmake build system (written in C++) even though a C compiler was available.
my fix back then was to manually write Makefiles for said packages.
nowadays larger projects with a lot of mindless contributors pull in idiotic dependencies out of lazyness: during build one file is generated with a python script, another with a perl script, a third one requires GNU sed, etc. these ppl do not see the pain they cause to ppl that like to compile stuff from source.

as you can see from sabotage's package of tinyproxy, we currently do not have a manpage since i patched out the dependency on a2x. i rather maintain a manual copy of the manpage that i copy in place as needed rather than pulling in the entire dependency chain to build a2x (from whatever package it comes from).
https://github.com/sabotage-linux/sabotage/blob/master/pkg/tinyproxy

**Comment by obnoxxx** [comment]
Hmm how to reply to this general rant against many projects?...

Firstly, if you choose to use a source-based distro, then you also choose to install everything that is needed to build the software you want to use. Since you will generally want to install many software packages on your system, that means it will be full of build-time dependencies. You want to install everything from source, you install all that is needed for it. That's my simple equation.

There are good reasons for the separation of build and runtime. It is not that you're not supposed to build stuff, but building has its challenges, it is a skillful and time-consuming task, and not every user can do it or has the time to do it. That work is done for the users by the distros who ship binaries. Also these distros put a lot of effort into delivering consistent packages and delivering updates in a timely manner (think about security releases...). Also  for production servers that may be security critical, it is best practice NOT to have build environments installed. The separation of build and runtime is hence not laziness, or a vice, but simply professional.

Secondly, as a consequence of the above, I don't buy the complaint that some projects use multiple tools (perl, python, sed, etc...): Even if each project only uses one tool, you will most probably need all of them anyways, since the different projects use different tools. So the complaint is vain to me.

Thirdly, I don't quite get the complaint about C++. Many projects use C++, and hence choosing not to provide a C++ compiler excludes these. Of course it is unfortunate that using cmake thereby excludes several projects that don't use C++ in their own code. But that is probably a manifestation of the fact that nowadays unix systems are broader than just C.

Coming back to the original request: Of course projects should not make it unnecessarily difficult to build, including requiring unnecessary packages for building. For the asciidoc requirement, I don't think it is unnecessary, it is consistent and yields the desired results. I could imagine to remove it at some point as a courtesy to source-based systems, but I can't spend the necessary time and energy on it right now. I would consider patches of course. :-)
