### ISSUE TITLE
The administrator of this proxy has not configured it to service requests from your host.

### ISSUE THREAD

**Issue by CryptoDude12** [tinyproxy/tinyproxy#221]
Hello, I  have setup Tinyproxy like in this tutorial: https://gist.github.com/webinista/812c20247a6c21e639ce
I skipped step 15 and use port 8888 to connect directly to the proxy in Chrome. I also removed both ConnectPorts to allow CONNECT on all ports. I only allow my IP in the config aswell. When I try to connect to an HTTPS site it gives this error: ERR_TUNNEL_CONNECTION_FAILED. 
And when I try to connect to an HTTP site it gives this error:
Access denied
The administrator of this proxy has not configured it to service requests from your host.

Generated by tinyproxy version 1.8.4.
This last message tells me that I am at least somehow connected to the proxy server. What am I doing wrong here?

**Comment by rofl0r** [comment]
> What am I doing wrong here?

for starters, you're using an obsolete version.

**Comment by CryptoDude12** [comment]
> > What am I doing wrong here?
> 
> for starters, you're using an obsolete version.

How can I install the 1.10 version? If I try sudo apt-get install tinyproxy it states the newest version (1.8.4-5) is already installed.

**Comment by rofl0r** [comment]
you need to compile it yourself, see `Installation` paragraph in README.md

**Comment by CryptoDude12** [comment]
Problem solved! Thank you so much, I've been hanging on this for hours

**Comment by rofl0r** [comment]
you're welcome!

**Comment by tamlyn** [comment]
For anyone else coming across this problem, it may be due to the `Allow` and `Deny` rules in [the config](https://tinyproxy.github.io/#documentation). 

By default (on MacOS Homebrew, at least) `/usr/local/etc/tinyproxy/tinyproxy.conf` says `Allow 127.0.0.1` which implies `Deny` everything else. You can either add more `Allow` lines (check the logs for clues like `Unauthorized connection from "localhost" [::1].`) or just comment out the existing `Allow` rule which then falls back to allow everything.
