### ISSUE TITLE
AddHeader and Config file maximum Line Length

### ISSUE THREAD

**Issue by sbrandtb** [tinyproxy/tinyproxy#226]
I'm trying to use tinyproxy just for adding a single header. The config looks like:

```cfg
Port 8002
AddHeader "some_header" "very long value that makes this line longer than 1023 characters"
PidFile "/tmp/tinyproxy.pid"
LogFile "/tmp/tinyproxy.log"
MaxClients 10
StartServers 1
Upstream localhost:8001
```

The issue here is that as soon as line 2 (or any line) gets longer than 1023 characters, tinyproxy breaks with `Syntax error on line 2. Unable to parse config file. Not starting.`

Is there a way to circumvent this?

**Comment by rofl0r** [comment]
conf.c
```c
/*
 * Parse the previously opened configuration stream.
 */
static int config_parse (struct config_s *conf, FILE * f)
{ 
        char buffer[1024];      /* 1KB lines should be plenty */  
```
POSIX defines a LINE_MAX macro, maybe that should be used instead (typically 4KB)
http://pubs.opengroup.org/onlinepubs/009695399/basedefs/limits.h.html
```
<limits.h>
{LINE_MAX}
    Unless otherwise noted, the maximum length, in bytes, of a utility's input line (either standard input or another file), when the utility is described as processing text files. The length includes room for the trailing <newline>.
    Minimum Acceptable Value: {_POSIX2_LINE_MAX}
```

**Comment by sbrandtb** [comment]
Tell me ignorant, high-level language script kiddie, but why do we need a line length limit in 2019?

If we do, the error message could be at least a bit more specific and the config file support line breaks - or in this case, any indirection like loading the header from a file.

**Comment by rofl0r** [comment]
> Tell me ignorant, high-level language script kiddie, but why do we need a line length limit in 2019?

because computers have limits too, and robustness.
if you allow unlimited everything, you need to use malloc() for everything, which can fail due to limited resources, and if you don't handle the failure, your program can crash in unexpected ways, even lethal ways (imagine software used in medical devices).
there was an attempt to create an OS without limits, and it failed horribly (it's called GNU Hurd).

> If we do, the error message could be at least a bit more specific

agreed. please provide a PR with one commit changing the limit to LINE_MAX, and another fixing the error message if the limit is hit.
