### ISSUE TITLE
URLs Filtering not working

### ISSUE THREAD

**Issue by talishka** [tinyproxy/tinyproxy#299]
I've configure my tinyproxy with the following rules and whitelist:

.cfg

```
FilterExtended On
FilterURLs On
FilterDefaultDeny Yes
Filter "/etc/tinyproxy/whitelist"
```

.whitelist

```
claro.com
google.com/recaptcha
microsoft.com
microsoftonline.com
```

And the issue is with "/" urls.. claro, microsoft, and microsoftonline are working perfectly, but when i add a url with a "/" i get the following error:

```
CONNECT   Apr 20 13:03:45 [3637]: Request (file descriptor 7): CONNECT www.google.com:443 HTTP/1.1
NOTICE    Apr 20 13:03:45 [3637]: Proxying refused on filtered url "www.google.com:443"
INFO      Apr 20 13:03:45 [3637]: no entity
```

**Comment by elyoas** [comment]
Your whitelist file should be only called 'whitelist' as specified in the config file, not '.whitelist'.

**Comment by talishka** [comment]
it's called whitelist. .whitelist and .cfg are not the names of the files, i was trying to make a point about which files i was talkin about.

**Comment by rofl0r** [comment]
could you describe your problem more accurately? is it that whitelist only works with urls not containing a slash ?

**Comment by talishka** [comment]
Yes, that's exactly the issue!

**Comment by rofl0r** [comment]
it seems the documentation about filtering was quite confusing, and rules need to be specified as posix regexes.
please take a look at the updated documentation https://github.com/tinyproxy/tinyproxy/commit/c4dc3ba007fe34d6b7704ffb5ec812a436c326e7 and let us know whether the issue persists after modifying your filter files to use posix BRE.

**Comment by Hollol** [comment]
Just wanted to report that I observe same behavior/bug as talishka. Configuration is same and my whitelist file looks like this (should be correct regex syntax, right?)

google\.com
https:\/\/ebay\.com
https:\/\/youtu\.be\/4DBZJSZdBlY

so, google and ebay without slash in URL are working, youtube with slash in URL not.

Any solution, fix or workaround for this problem? By the way, I am using tinyproxy as an URL filter for my children's computers.

**Comment by rofl0r** [comment]
@Hollol the filtering mechanism has 2 works modes: domain-based (what you are using) and URL-based. 
you can't mix the 2 (google.com is a domain, `http://google.com` is an url).
you can toggle to url based with `FilterURLs On` in config.
also regular slashes don't need to be escaped. you can also get rid of the https:// prefix as the regex will match even without. i'm not even certain whether the URL-based filter can work on https URL, since connections are done via CONNECT method and encrypted. so the only thing tinyproxy gets to see there is the domain part.

if you'd use the url-based filter

**Comment by Hollol** [comment]
@rofl0r Thanks for the information. In config I have url based filtering activated (FilterURLs On). Indeed, I was not aware, that I am not able to mix both modes and that I do not have to escape the slash. I will try again with the modified filter list. In case https url based filtering will not work,I (unfortunately) have to find another solution :-(

**Comment by rofl0r** [comment]
since it's impossible to block *any* youtube video that's inadequate for kids, you could just block youtube completely.
you can then allow them to use it only under parental supervision.

**Comment by cacilhas** [comment]
Considering `tinyproxy` has a URL-based blacklist, it should be  possible to block  specific YouTube videos by their URL, otherwise, `FilterURLs` would be a **lie**, which would make `tinyproxy` a **piece of shit**.

I’m trying to do exactly that, but `tinyproxy` is ignoring the blacklist. Either I’m doing something wrong (I hope), or I’m right and `tinyproxy` is **useless**.

My `/etc/tinyproxy/tinyproxy.conf` contains:
```
Filter "/etc/tinyproxy/blocks.cfg"
FilterType ere
FilterURLs Yes
FilterCaseSensitive No
FilterDefaultDeny No
```

And `/etc/tinyproxy/blocks.cfg` contains:
```
.*SteveGoesHard.*
```

But I’m still able to access URLs containing `SteveGoesHard` through the proxy. What am I doing wrong (considering `tinyproxy` is any useful)?

**Comment by rofl0r** [comment]
as mentioned earlier, URL based filtering works only for HTTP, not HTTPS. the feature was devised in a time where HTTPS was only used for e-banking, today it's everywhere. use domain-based filtering instead.
