### ISSUE TITLE
About the usages of the transparent and reverse proxy for tinyproxy.

### ISSUE THREAD

**Issue by hongyi-zhao** [tinyproxy/tinyproxy#360]
On Ubuntu 20.04, I compiled and installed the git master version of `tinyproxy` with the following steps:
```
$ sudo apt build-dep tinyproxy
$ git clone https://github.com/tinyproxy/tinyproxy.git tinyproxy.git && cd tinyproxy.git 
$ ./autogen.sh
$ LDFLAGS=-static ./configure --enable-xtinyproxy --enable-filter --enable-upstream --enable-transparent --enable-reverse  --enable-silent-rules
$ make
$ sudo make install
```
But I still can't figure out the usages of the transparent and reverse proxy for `tinyproxy`. Any hints will be highly appreciated. 

Regards,
HY

**Comment by rofl0r** [comment]
`man 5 tinyproxy.conf` - it also helps to search here in github issues to see example config and scenarios posted by user.

**Comment by hongyi-zhao** [comment]
Thanks a lot for your notes. It seems that `tinyproxy` is not professional for these types of jobs. More specifically, nginx is more suitable as a reverse proxy, while squid is better as [a transparent proxy](https://tldp.org/HOWTO/TransparentProxy.html).

**Comment by rofl0r** [comment]
> tinyproxy is not professional for these scenarios

what makes you think so?

but you're right in that it is not *professional* in the proper meaning of the word, because none of the authors of tinyproxy get paid for their work or support.

> nginx is more suitable as a reverse proxy

well, i guess that depends on your needs. tinyproxy works just fine as reverse proxy, though i guess nobody tested/benchmarked it with 10s of thousands of connection, which seems to be the market targeted by nginx.

> while squid is better as a transparent proxy

where's proof for these claims ?

**Comment by hongyi-zhao** [comment]
All my claims are based on the statistical feelings of all the tools I have seen that act as such proxies.

**Comment by rofl0r** [comment]
ah ok, based on feelings. alright. :)
