### ISSUE TITLE
Q: best way to add a cache alongside tinyproxy?

### ISSUE THREAD

**Issue by gingerbeardman** [tinyproxy/tinyproxy#429]
## Tinyproxy version
1.11.0 stable

## Issue

I use tinyproxy to help speed up requests to a couple of slow and inaccessible servers on the other side of the world by routing them through a fast data centre.

I understand that tinyproxy does not do any caching, so I'd like to add a cache alongside tinyproxy so that static assets are served even more quickly.

My setup is:
- OCI compute instance (ARM64)
- Ubuntu 20.04
- Docker container: ajoergensen/tinyproxy

Any ideas or thoughts appreciated.

Thanks!

**Comment by rofl0r** [comment]
cacheing http proxies these days are of limited help because the majority of sites is https-only.
one would basically need a proxy that intercepts https requests and injects its own certificate, which has to be whitelisted in the browser. i suspect there might be some proxy servers that can do this (privoxy, owasp?) but then one can use those on their own without tinyproxy in the middle.

**Comment by gingerbeardman** [comment]
Thanks, I'll look into those.

**Comment by gingerbeardman** [comment]
I understand that the pages are encrypted so can't be easily cached, but the assets are not so it would be those that I would like caching. Mostly images, but also CSS & JS.

**Comment by rofl0r** [comment]
the assets are fetched via http ? sounds unlikely, as it would allow MITM attacks injecting malicious js into your browser. speaking of browsers, some plugins/addons might exist caching popular js frameworks.

**Comment by gingerbeardman** [comment]
I see what you mean. Everything is https

I also don't think I understand exactly how tinyproxy works so I'll look into that.
