### ISSUE TITLE
Anonymous not working?

### ISSUE THREAD

**Issue by egabosh** [tinyproxy/tinyproxy#503]
Moin,

As I understand the "Anonymous" Option in tinyproxy.conf should block defined data for "Websites".
Using for example https://www.deviceinfo.me/ this doesn't work.

Here my config:
```
User tinyproxy
Group tinyproxy
Port 8888
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/tinyproxy.log"
Syslog Off
LogLevel Critical
PidFile "/run/tinyproxy/tinyproxy.pid"
XTinyproxy No
MaxClients 100
Allow 127.0.0.1
Allow ::1
Allow 192.168.0.0/16
Allow 172.16.0.0/12
Allow 10.0.0.0/8
ViaProxyName "tinyproxy"
DisableViaHeader Yes
#####
Anonymous "Accept-Language"
#####
ConnectPort 443
ConnectPort 563
```
As I understand every Header but Accept-Language should be blocked. But browsing to https://www.deviceinfo.me/ shows User-Agent and many other headers in a correct way.
Am I doing something wrong or is this a bug?

**Comment by rofl0r** [comment]
this feature, like all other features that manipulate headers, only works with http endpoints, not https. in order to provide it for TLS enabled sites, we'd have to turn tinyproxy into a TLS-intercepting proxy and as such every user would have to install tinyproxy's certificate into their browser. this would also mean that tinyproxy would require to use and interface with a TLS/SSL library, and burden the user with certificate setup. since this is outside the scope of tinyproxy, consider these features obsolete in the https-everywhere age.

**Comment by ianmarcinkowski** [comment]
Hey, can this issue be closed?  (I was just browsing the issues while implementing a feature and noticed a few that could could probably be closed to keep the issues clean)
