### ISSUE TITLE
Response to a failed authentication should be 407 instead of 401

### ISSUE THREAD

**Issue by vsalavatov** [tinyproxy/tinyproxy#532]
In my case, this confuses java http client. It then asks for credentials for the server instead of new credentials for the proxy. Hence, wrong proxy credentials are not invalidated and instead are reused, which in turn leads to all requests failing with 401 status.

https://stackoverflow.com/questions/5508822/http-response-to-invalid-proxy-authentication

If I'm not mistaken, this is the place that should be fixed: https://github.com/tinyproxy/tinyproxy/blob/c4df45b7e416dc1a26bb4e4511e1e7de08fd49af/src/reqs.c#L1695

**Comment by Gruummy** [comment]
I have seen this problem also ... and agree, that it should responde in case of a request which should be proxied, and the credential in proxy-authorization is wrong -> with http 407

In case that the "stats" host is the target of a request, and no proxy action to some other endpoints needs to happen, then the response needs to be http 401. In this use case tinyproxy is a server on it own.

https://www.rfc-editor.org/rfc/rfc2617.html#section-1.2

`
   If the origin server does not wish to accept the credentials sent
   with a request, it SHOULD return a 401 (Unauthorized) response. The
   response MUST include a WWW-Authenticate header field containing at
   least one (possibly new) challenge applicable to the requested
   resource. If a proxy does not accept the credentials sent with a
   request, it SHOULD return a 407 (Proxy Authentication Required). The
   response MUST include a Proxy-Authenticate header field containing a
   (possibly new) challenge applicable to the proxy for the requested
   resource.
`

I think i will try this fix as next when my current pull request potentially gets a chance to be accepted.

@rofl0r 
What do you think about this issue ?
... are you bored of my first "C" toddler contribution attempts ... or would it be ok that i also try to do one more pull request about this issue ?

**Comment by rofl0r** [comment]
i've been reading the relevant RFC sections when this was posted, but the language used is everything but clear. the part you quoted uses "SHOULD" so it's not a requirement. also what's the difference between "does not wish to accept" vs "does not accept"? to figure out what's right or wrong one would have to read everything three times and take it apart under a microscope. it's probably less effort to see what other popular HTTP services implement.

**Comment by Gruummy** [comment]
I have more than 10 years of experience in daily business with multiple proxy/server products in this topic.

And i can tell you, that:
- http 401 is the response / error case of "authorization" header credentials not valid or not existing -> if required
- http 407 is the response / error case of "proxy-authorization" header credentials not valid or not existing -> if required

http 403 permission denied is the follow up error case of servers which validate the authorization header, the credentials are valied, but the identitiy is not allowed to access the requested ressource (can not be created be proxy itself. Only in case of webserver usecase)

This also clearly explains the problem which the java http client faces.

You are right, the RFC is here not glasclear, but even if there is a "should" mentioned, it makes it not better for the guys and girls which face here inconsistent handling. The proposed change would make the behaviour clear, and also "clean".

This change is pretty easy and can not have negative sideeffects in tinyproxy when we implement it this way.
... both error codes cause "i don't let you in". 

It only will make it really better in the proxy authentication verification.

A litte bit trickier probably the use case of the tinyproxy "stats" host can evolve related to backward compatible / incompatible changes related to a fix at this point.

Until now i have not tested the current behaviour of it. 

But my first thoughts go into the direction, that this is already today as http 401 responded .. but i had not checked if there the "authorization" header will be used for validation, or if this endpoint is not protected at all.

The current code logic  is here not directly clear to me.

Should the "stats" host endpoint also have user/password validation with same credential like the proxy use case ... or not ?
What is the "Is implemented currently this way" behaviour ?

**Comment by Gruummy** [comment]
https://github.com/tinyproxy/tinyproxy/issues/532

Hi @rofl0r

i have done a little bit related research and have following recognized:

- tinyproxy had added support of basic-authentication on the proxy itself in February 2018
  https://github.com/tinyproxy/tinyproxy/commit/8db511b9bff5dfa61a9448659e28ce54d9aa8869
- At the same time with a different commit the usage of http status code 407 was introduced 
  https://github.com/tinyproxy/tinyproxy/commit/bd04ed00d8b9bac68eaf6f3e7c739ceef043e679
- Before this point was only http error response code 403 implemented (no 401 or 407)
- tinyproxy internally somehow is still stuck to http 1.0 protocol. 
  Since a special commit in 2021 a "fake" http 1.1 mode in communication with upstream was implemented.
  https://github.com/tinyproxy/tinyproxy/issues/152
  https://github.com/tinyproxy/tinyproxy/commit/a869e71ac382acb2a8b4442477ed675e5bf0ce76
- There is still a open issue about http 1.1 support of tinyproxy
  https://github.com/tinyproxy/tinyproxy/issues/437

Now the "tricky" part is comeing:

- http 1.0 per definition do not support http status code 407
  https://datatracker.ietf.org/doc/html/rfc1945#section-9.4
- http status code 407 was first time introduced with http 1.1 specification
  https://datatracker.ietf.org/doc/html/rfc2068#section-10.4.8

Per RFC definitions when tinyproxy still uses http 1.0 protocol im communication with the client, there is no support of statuscode 407.

I think we should now fix this Problem.
What is you opinion on this ?

Directly in front of follow up discussion:
Even when there is support of keepalive also in http 1.1 spec. It is not a MUST on Proxy side.
As long the proxy server process sends a "connection close" after the request is finished to the Client --> everything is in a short run fine. There is no Need to support keepalive directly with possible introduction of http 1.1 in the client communication of tinyproxy.
--> https://datatracker.ietf.org/doc/html/rfc9112#section-9.3

```
HTTP/1.1 defaults to the use of "persistent connections", allowing multiple requests and responses to be carried over a single connection. HTTP implementations SHOULD support persistent connections.

…

A server that does not support persistent connections MUST send the "close" connection option in every response message that does not have a 1xx (Informational) status code.
```

**Comment by rofl0r** [comment]
how does this fix look? https://github.com/tinyproxy/tinyproxy/pull/549

as for "407 isnt officially supported by HTTP/1.0" i doubt any client that gets the code actually checks whether it is using HTTP 1.0 and then refuses to do the right thing. let's be pragmatic here and not make up issues that most likely are none.

also why do you bring up connection: keepalive here ? i don't see the relation to this issue.

**Comment by Gruummy** [comment]
I only mentioned the point about keepalive to show that you don't have to deal with the full supported options of http 1.1 if you are considering introducing http 1.1 partially in the communication with the client.

Because of your pull request, I would like to take a closer look at it later.

At first glance, however, it looks to me like a step in the wrong tactical direction, since this goes back to the http 401 error response code in the case of proxy authentication problems.

That would then be http 1.0 compliant (in theory), but in my view you are completely on the fence here, since every client can have implemented support for http1.0 / http 1.1 differently in a more or less complete way.

Personally, I would think more along the lines of why not answer the answer / error response with the http 1.1 protocol, then the 407 code would be properly supported, as would the header names that would have to be used. And this would then be fully http 1.1 compliant for this one request / error response.

Why not respond "authentication on proxy side failed" usecase in the following http 1.1 way ?

```
< HTTP/1.1 407 Proxy Authentication Required
< Server: tinyproxy
< Content-Type: text/html
< Proxy-Authenticate: Basic realm="Tinyproxy"
< Connection: close
```

Is there a deeper reason why you want to stick to using HTTP 1.0 for client communication?

I mean, is there an important reason that is not immediately obvious to me, but that I should know better?

**Comment by rofl0r** [comment]
> But i asked me already multiple times why the "stats" endpoint needs to have authorization validation at all ?

it's custom in organizations that only the IT staff has access to information the user doesn't need to know. i haven't heard any complaints about the behaviour so far.

> Personally, I would think more along the lines of why not answer the answer / error response with the http 1.1 protocol

is it even "legal" to answer a HTTP/1.0 request with HTTP/1.1 ? IIRC not.
currently we simply echo the version the client used, which seems to work well in practice.

in general we don't want to pretend to fully support HTTP/1.1 as there are some changes that would require serious rework of internals. i don't remember the exact details, but iirc some were raised here in issues and commented on. also most of those changes affect only the usecase HTTP -> HTTP, which is a tiny and continuously shrinking percentage of the requests since almost all websites transitioned to HTTPS. that degrades tinyproxy to a dumb man in the middle, getting a CONNECT request, and then just bouncing data back and forth.

**Comment by Gruummy** [comment]
Yes, it is possible and allowed for a proxy server to respond to a request sent over HTTP 1.0 with HTTP 1.1. The HTTP versions are designed to be backwards compatible, which means that a client using an older version should be able to communicate with a server using a newer version, and vice versa. The proxy could use additional headers or behaviors from HTTP 1.1 in its response, but it should ensure that the response is still understandable and correctly processed by an HTTP 1.0 client.

There can of course still be problems for clients that only support HTTP 1.0.

Such clients would already have problems today if they received an HTTP response code 407.

For all clients that properly support HTTP 1.1, however, we would then be cleanly within the RFC spec.
