### ISSUE TITLE
1.11.2 doesn't create /run/tinyproxy anymore, therefore it can't start anymore without creating it manually

### ISSUE THREAD

**Issue by thomas-merz** [tinyproxy/tinyproxy#552]
## Tinyproxy version
1.11.2

## Issue
With 1.11.1 there was a directory /run/tinyproxy created which is now missing with 1.11.2:

```
# rpm -ql tinyproxy
/etc/logrotate.d/tinyproxy
/etc/tinyproxy
/etc/tinyproxy/tinyproxy.conf
/run/tinyproxy
/usr/bin/tinyproxy
/usr/lib/.build-id
/usr/lib/.build-id/a1
/usr/lib/.build-id/a1/5376086cdb9e7a53886de6f25f1d2e8b00970c
/usr/lib/systemd/system/tinyproxy.service
/usr/lib/tmpfiles.d/tinyproxy.conf
/usr/share/doc/tinyproxy
/usr/share/doc/tinyproxy/AUTHORS
/usr/share/doc/tinyproxy/COPYING
/usr/share/doc/tinyproxy/NEWS
/usr/share/doc/tinyproxy/README
/usr/share/doc/tinyproxy/README.md
/usr/share/doc/tinyproxy/http-error-codes.txt
/usr/share/doc/tinyproxy/http-rfcs.txt
/usr/share/man/man5/tinyproxy.conf.5.gz
/usr/share/man/man8/tinyproxy.8.gz
/usr/share/tinyproxy
/usr/share/tinyproxy/debug.html
/usr/share/tinyproxy/default.html
/usr/share/tinyproxy/stats.html
/var/log/tinyproxy
```
But with 1.11.2
```
# rpm -ql tinyproxy
/etc/tinyproxy
/etc/tinyproxy/tinyproxy.conf
/usr/bin/tinyproxy
/usr/lib/.build-id
/usr/lib/.build-id/00
/usr/lib/.build-id/00/0052d6e1022a647e7b06768828e9081c379ca3
/usr/lib/systemd/system/tinyproxy.service
/usr/share/doc/tinyproxy
/usr/share/doc/tinyproxy/AUTHORS
/usr/share/doc/tinyproxy/NEWS
/usr/share/doc/tinyproxy/README
/usr/share/doc/tinyproxy/README.md
/usr/share/licenses/tinyproxy
/usr/share/licenses/tinyproxy/COPYING
/usr/share/man/man5/tinyproxy.conf.5.gz
/usr/share/man/man8/tinyproxy.8.gz
/usr/share/tinyproxy
/usr/share/tinyproxy/debug.html
/usr/share/tinyproxy/default.html
/usr/share/tinyproxy/stats.html
````

Error message:
```
tinyproxy[1156]: tinyproxy: Could not create file /run/tinyproxy/tinyproxy.pid: No such file or directory
tinyproxy[1156]: /usr/bin/tinyproxy: Could not create PID file.
systemd[1]: tinyproxy.service: Main process exited, code=exited, status=71/OSERR
systemd[1]: tinyproxy.service: Failed with result 'exit-code'.
```

So `tinyproxy` won't start anymore without a little help (`mkdir`) 😢  (even when running `tinyprocxy` as `root` and not as a non-privileged user!)

**Comment by rofl0r** [comment]
this sounds like a packaging bug to me. nothing in tinyproxy itself related to this was changed between 1.11.1 and .2. did you report this with your distro - which i assume is either fedora or suse ?

**Comment by thomas-merz** [comment]
It's EPEL (Fedora), so I [created a bug in Fedora EPEL](https://bugzilla.redhat.com/show_bug.cgi?id=2302250).

**Comment by rofl0r** [comment]
seems to be from this change: https://src.fedoraproject.org/rpms/tinyproxy/c/2d77f1aecd063f6a437289aec71fa40299a73407?branch=rawhide

it's conceptually doing the right thing, but it's removing the empty dir - which causes the error with either a custom config specifying a pidfile or with a systemd service that's still using the old fork style. so the ghost dir line should be added back.

**Comment by obnoxxx** [comment]
@rofl0r  wrote:
> seems to be from this change: https://src.fedoraproject.org/rpms/tinyproxy/c/2d77f1aecd063f6a437289aec71fa40299a73407?branch=rawhide
> 
> it's conceptually doing the right thing, but it's removing the empty dir - which causes the error with either a custom config specifying a pidfile or with a systemd service that's still using the old fork style. so the ghost dir line should be added back.


Nice analysis, thanks!

**Comment by carlwgeorge** [comment]
Howdy, Fedora and EPEL package maintainer here.

> It's EPEL (Fedora), so I [created a bug in Fedora EPEL](https://bugzilla.redhat.com/show_bug.cgi?id=2302250).

I replied on that bug.  In summary, the EPEL 8 package works out of the box, there's nothing to fix.

> it's conceptually doing the right thing, but it's removing the empty dir

That directory was removed in Fedora Rawhide and Fedora 40 before release, but it was not removed from any existing stable Fedora or EPEL releases.  It was never included in any EPEL 8 build.  It seems like @thomas-merz had an RPM installed from somewhere else that did include that directory.  EPEL can't guarantee clean upgrade paths from RPMs installed from other repos.

> which causes the error with either a custom config specifying a pidfile

This is the actual problem here I think.  The default config file shipped in the package does not specify a PidFile and allows the service to start without error.

> so the ghost dir line should be added back.

Just adding the ghost line means the package will claim ownership of the directory when it exists, but it will not create it.  That wouldn't solve the issue here.  The real fix is to remove the PidFile directive from the custom local config file.

**Comment by rofl0r** [comment]
just out of curiosity - how does fedora treat existing config files ?  in sabotage, we never overwrite existing stuff in /etc at package installation time. if fedora has a similar policy, then i would argue that it should keep the directory structure that's needed for "legacy" configs.

**Comment by carlwgeorge** [comment]
If the file is marked as [`%config(noreplace)`](https://rpm-software-management.github.io/rpm/manual/spec.html#config) (as is [recommended by the Fedora Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_configuration_files)) then rpm has logic to not overwrite the file if it has deviations from the default, and instead it will write the new file with an `.rpmnew` suffix.  If the file is unchanged (identical to the file in the old package version) then it will be replaced by the file in the new package version.  [Here is a chart](https://www.cl.cam.ac.uk/~jw35/docs/rpm_config.html) that explains all the possibilities.

If there had previously been an EPEL 8 package that included a config file that used the `/run/tinyproxy/` path, then I could understand the argument that the package should keep the directory just in case, but that's not the case.  What if someone files a bug report that their service won't start because the package doesn't contain `/var/lib/tinyproxy/`?  Should the EPEL package add a directory that it never had before just to accommodate an arbitrary custom config file?

I haven't always been the maintainer of this package in Fedora and EPEL.  Last year I realized the package had been orphaned in Fedora, so I adopted it to keep it from being retired.  I also knew there were outstanding requests to add the package to EPEL 8 and EPEL 9.  Before adding the package to those EPEL releases I went through and made several improvements to the package.  For example, previously the Fedora package had it's own config file that was different from the upstream default from this repo.  I chose to switch the package to the [upstream config file with just the User and Group modified](https://src.fedoraproject.org/rpms/tinyproxy/c/4b9e1bb7b6b561036a9b1eed21817f6a68315588?branch=rawhide), but only in Fedora development releases.  The initial packages for EPEL 8 and EPEL 9 included this change, but since they were the initial packages it wasn't a change, just how the package worked from the start.

**Comment by rofl0r** [comment]
alright, thanks for the info. i guess we can close this, at least here. cheers!

**Comment by carlwgeorge** [comment]
Of course, happy to help!  If you get any other issues reported that you think may be due to the Fedora/EPEL packaging, feel free to `@` mention me, or just direct the reporter directly to bugzilla.  I'd also be happy to help onboard any of the upstream maintainers to become Fedora/EPEL packagers so they can co-maintain the packages, if they're interested.

**Comment by thomas-merz** [comment]
Problem solved by removing non-default PidFile directive in the configuration file 👍🏼
