### ISSUE TITLE
open url 100% : Access Denied

### ISSUE THREAD

**Issue by marklove5102** [tinyproxy/tinyproxy#558]
system :archlinx
dns :china
tinyproxy ver :1.11.2-2
Browser :firefox  or  edge 
url :http://bumimi17.com/
100%   Access Denied

url https://cn.bing.com/  There is no such problem

**Comment by rofl0r** [comment]
since HTTP (unlike HTTPS) isn't encrypted, the GFW can easily detect that you use a proxy and may decide to block your request depending on the target URL, target location, or proxy location. as i'm not an expert on GFW, i can't really help here. a potential solution that comes to mind is using an ssh connection to a server outside the country and use ssh's built-in socks5 feature (ssh -D localhost:1080). you could run a local tinyproxy with upstream pointing to your local socks5 port in case your browser supports only http proxies. to the GFW it would appear like regular encrypted SSH traffic. closing this issue as it's nothing we can fix on our end.

**Comment by marklove5102** [comment]
> since HTTP (unlike HTTPS) isn't encrypted, the GFW can easily detect that you use a proxy and may decide to block your request depending on the target URL, target location, or proxy location. as i'm not an expert on GFW, i can't really help here. a potential solution that comes to mind is using an ssh connection to a server outside the country and use ssh's built-in socks5 feature (ssh -D localhost:1080). you could run a local tinyproxy with upstream pointing to your local socks5 port in case your browser supports only http proxies. to the GFW it would appear like regular encrypted SSH traffic. closing this issue as it's nothing we can fix on our end.

我没有翻墙
主机无网(通过虚拟机 tinyproxy 或者 gost 给浏览器提供网络)
现在的问题是 在edge gost  有概率不能打开很小   firefox 百分百打不开
tinyproxy 是百分百  edge gost 都不能打开.
所以我认为是tinyproxy的问题.

**Comment by marklove5102** [comment]
@rofl0r

**Comment by rofl0r** [comment]
sorry, but i can only answer to english requests. maybe someone who speaks mandarin or whatever language your hieroglyphs are written in can help.

**Comment by marklove5102** [comment]
@rofl0r 
OK
my pc ( virtoalbox archlinux install  tinyproxy)  edge firefox -> open  http://bumimi17.com/
100% : Access Denied
my pc ( virtoalbox archlinux install  [gost](https://github.com/ginuerzh/gost)) edge -> open  http://bumimi17.com/ isok
so  this bug?

pc-virtoalbox-net------->bumimi17.com

**Comment by colemar** [comment]
@marklove5102
If you are behind the chinese Great Firewall there are better solutions than Tinyproxy.

If you insist on using it, at least install Tinyproxy on a machine which is outside the Great Firewall (a remote machine), install Stunnel on the same machine (listening on port 443 and connecting to Tinyproxy port), then tell your local browser to use `https://user:password@tinyproxyhost.xyz` as proxy, where tinyproxyhost.xyz is the FQ domain name of the remote machine and user:password are the same credentials as `BasicAuth user password` in tinyproxy.conf
Beware that you must also have a TLS certificate (for example Let's Encrypt) for Stunnel that matches the name tinyproxyhost.xyz
