### ISSUE TITLE
Don’t spawn threads for each connection.

### ISSUE THREAD

**Issue by ytrezq** [tinyproxy/tinyproxy#76]
Creating threads is still costly *(an empty thread takes 8Mb on x86)*. You’ll see that most web brothers use a single thread for handling all ajax *(unless requested by the application through a webworker)* requests.

Concerning incoming connections you can look to nginx for example.

I recognize I never understood how this was done.

**Comment by rofl0r** [comment]
> an empty thread takes 8Mb on x86

that's only true for glibc, and it's only true if the created thread is left at the default stacksize.
the default for glibc is 8MB, for musl libc 80KB.
it's probably safe for this use case here to set the stacksize of new threads using pthread_set_attr() before pthread_create().
more info: https://bugzilla.libsdl.org/show_bug.cgi?id=2019

**Comment by ytrezq** [comment]
@rofl0r : this could be done from tinyproxy itself.

But generally, creating thread is costly, and it is only required for parallel execution. You don’t want to execute requests in parallel you want to handle all connection. Most advanced servers don’t use thread for this *(or at least, they use a thread pool)*.

**Comment by rofl0r** [comment]
> @rofl0r : this could be done from tinyproxy itself.

yes, that's what i suggest

> But generally, creating thread is costly

i agree that it's relatively costly on GLIBC. on musl it is quite fast though, maybe 1000-3000 cycles. so you probably should not do it to achieve parallelization for short computations. usually the lifespan of a connection is much longer though; and the network latency is orders of magnitude higher than the thread spinup time. this is probably only an issue if you need to deal with thousands of connections, and i'm not sure if tinyproxy wants to support that.
anyway, if it doesnt make the code much more complicated, evaluating thread pools might be an option.

**Comment by ytrezq** [comment]
@rofl : How to have to handle thousands connections ? 10 users using very old versions of opera ?

**Comment by nihilus** [comment]
Well, I've some speed penalties when I use it as a reverse-proxy on top of OpenWRT-style router with mini_httpd as backend server.

**Comment by rofl0r** [comment]
turns out tinyproxy doesn't use any threads at all. it justs forks() once per connection. which means this entire discussion is moot.

as for 

> How to have to handle thousands connections ?

i'm indeed curious how this is done in other programs, but i suspect they use a fixed number of worker threads/processes, each of which is responsible to deal with several client fd, which in turn are watched via poll() or a similar mechanism. that means if you really had like 100K connected clients, each of whom would be sending/receiving data at the very same time, in fact only N clients would be served in parallel, where N is the number of worker threads.
