### ISSUE TITLE
can tinyproxy use asynchronous way to handle connection.

### ISSUE THREAD

**Issue by hanbaga** [tinyproxy/tinyproxy#8]
the function of relay_connection is synchronous to read/write data from/to socket.   can change it.

**Comment by obnoxxx** [comment]
What would be the benefit? There is one process per connection. So for a tinyproxy process there is just one connection to relay, and hence I don't see a direct advantage.

**Comment by hanbaga** [comment]
the benefit is that one process can handle more connection not only one.  that will decrease the count of process and machine's load.

**Comment by obnoxxx** [comment]
Well, this is not currently tinyproxy's design.
Also TP's memory footprint is so small that it is perfectly OK to run a few hundred or a few thousand TP processes simultaneously. Do you experience an unbearable load put upon your system by tinyproxy?

I understand that this might be interesting. I had started to think about making tinyproxy single-process with an async event loop at some point. Rather out of interest, not because I was suffering from a bad resource problem.. :-) But it is not as easy as making the relay_connection function async. The whole project needs to be rewritten essentially. And you need to be aware that there are blocking syscalls involved (reading/writing from socket, etc), so that when you have all in one process, then all clients may experience a much worse performance, unless you do some additional multi-threading...

Just my 2 cents on the problem space.

**Comment by hanbaga** [comment]
recently I request some slow resources using tinyproxy.  the count of child process will increase horribly once Qps is big. 

but TP is a  better tool for me as a http proxy.    thank you.
